// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: segmentation/segment.proto

package segmentation

import (
	common "github.com/MelnikovNA/User-segmentation/proto/codegen/go/common"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentObject) Reset() {
	*x = SegmentObject{}
	mi := &file_segmentation_segment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentObject) ProtoMessage() {}

func (x *SegmentObject) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentObject.ProtoReflect.Descriptor instead.
func (*SegmentObject) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentObject) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SegmentObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentRequest) Reset() {
	*x = CreateSegmentRequest{}
	mi := &file_segmentation_segment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentRequest) ProtoMessage() {}

func (x *CreateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentRequest.ProtoReflect.Descriptor instead.
func (*CreateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSegmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentResponse) Reset() {
	*x = CreateSegmentResponse{}
	mi := &file_segmentation_segment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentResponse) ProtoMessage() {}

func (x *CreateSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentResponse.ProtoReflect.Descriptor instead.
func (*CreateSegmentResponse) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateSegmentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSegmentRequest) Reset() {
	*x = DeleteSegmentRequest{}
	mi := &file_segmentation_segment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentRequest) ProtoMessage() {}

func (x *DeleteSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSegmentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateSegmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SegmentNewName string                 `protobuf:"bytes,2,opt,name=segment_new_name,json=segmentNewName,proto3" json:"segment_new_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSegmentRequest) Reset() {
	*x = UpdateSegmentRequest{}
	mi := &file_segmentation_segment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSegmentRequest) ProtoMessage() {}

func (x *UpdateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSegmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSegmentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSegmentRequest) GetSegmentNewName() string {
	if x != nil {
		return x.SegmentNewName
	}
	return ""
}

type GetUserSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSegmentsRequest) Reset() {
	*x = GetUserSegmentsRequest{}
	mi := &file_segmentation_segment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSegmentsRequest) ProtoMessage() {}

func (x *GetUserSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSegmentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserSegmentsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentObject       `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSegmentsResponse) Reset() {
	*x = GetUserSegmentsResponse{}
	mi := &file_segmentation_segment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSegmentsResponse) ProtoMessage() {}

func (x *GetUserSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSegmentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserSegmentsResponse) GetSegments() []*SegmentObject {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *GetUserSegmentsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AssignRandomSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Percentage    float32                `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRandomSegmentsRequest) Reset() {
	*x = AssignRandomSegmentsRequest{}
	mi := &file_segmentation_segment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRandomSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRandomSegmentsRequest) ProtoMessage() {}

func (x *AssignRandomSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRandomSegmentsRequest.ProtoReflect.Descriptor instead.
func (*AssignRandomSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{7}
}

func (x *AssignRandomSegmentsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssignRandomSegmentsRequest) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type ListSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsRequest) Reset() {
	*x = ListSegmentsRequest{}
	mi := &file_segmentation_segment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsRequest) ProtoMessage() {}

func (x *ListSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{8}
}

func (x *ListSegmentsRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentObject       `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsResponse) Reset() {
	*x = ListSegmentsResponse{}
	mi := &file_segmentation_segment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsResponse) ProtoMessage() {}

func (x *ListSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segmentation_segment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_segmentation_segment_proto_rawDescGZIP(), []int{9}
}

func (x *ListSegmentsResponse) GetSegments() []*SegmentObject {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *ListSegmentsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_segmentation_segment_proto protoreflect.FileDescriptor

const file_segmentation_segment_proto_rawDesc = "" +
	"\n" +
	"\x1asegmentation/segment.proto\x12\fsegmentation\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\"3\n" +
	"\rSegmentObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x14CreateSegmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"W\n" +
	"\x15CreateSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"&\n" +
	"\x14DeleteSegmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"P\n" +
	"\x14UpdateSegmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x10segment_new_name\x18\x02 \x01(\tR\x0esegmentNewName\"(\n" +
	"\x16GetUserSegmentsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x17GetUserSegmentsResponse\x127\n" +
	"\bsegments\x18\x01 \x03(\v2\x1b.segmentation.SegmentObjectR\bsegments\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"M\n" +
	"\x1bAssignRandomSegmentsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x02R\n" +
	"percentage\"%\n" +
	"\x13ListSegmentsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x83\x01\n" +
	"\x14ListSegmentsResponse\x127\n" +
	"\bsegments\x18\x01 \x03(\v2\x1b.segmentation.SegmentObjectR\bsegments\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\r.common.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xb3\x05\n" +
	"\x0eSegmentService\x12s\n" +
	"\rCreateSegment\x12\".segmentation.CreateSegmentRequest\x1a#.segmentation.CreateSegmentResponse\"\x19\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/segments\x12a\n" +
	"\fDeletSegment\x12\".segmentation.DeleteSegmentRequest\x1a\x10.common.Response\"\x1b\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x10*\x0e/segments/{id}\x12`\n" +
	"\rUpdateSegment\x12\".segmentation.UpdateSegmentRequest\x1a\x10.common.Response\"\x19\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/segments\x12\x80\x01\n" +
	"\x0fGetUserSegments\x12$.segmentation.GetUserSegmentsRequest\x1a%.segmentation.GetUserSegmentsResponse\" \x92A\x02b\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/user/segments/{id}\x12p\n" +
	"\x14AssignRandomSegments\x12).segmentation.AssignRandomSegmentsRequest\x1a\x10.common.Response\"\x1b\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x10\x1a\x0e/segments/{id}\x12r\n" +
	"\fListSegments\x12!.segmentation.ListSegmentsRequest\x1a\".segmentation.ListSegmentsResponse\"\x1b\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x10\x12\x0e/segments/{id}BGZEgithub.com/MelnikovNA/User-segmentation/proto/codegen/go/segmentationb\x06proto3"

var (
	file_segmentation_segment_proto_rawDescOnce sync.Once
	file_segmentation_segment_proto_rawDescData []byte
)

func file_segmentation_segment_proto_rawDescGZIP() []byte {
	file_segmentation_segment_proto_rawDescOnce.Do(func() {
		file_segmentation_segment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_segmentation_segment_proto_rawDesc), len(file_segmentation_segment_proto_rawDesc)))
	})
	return file_segmentation_segment_proto_rawDescData
}

var file_segmentation_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_segmentation_segment_proto_goTypes = []any{
	(*SegmentObject)(nil),               // 0: segmentation.SegmentObject
	(*CreateSegmentRequest)(nil),        // 1: segmentation.CreateSegmentRequest
	(*CreateSegmentResponse)(nil),       // 2: segmentation.CreateSegmentResponse
	(*DeleteSegmentRequest)(nil),        // 3: segmentation.DeleteSegmentRequest
	(*UpdateSegmentRequest)(nil),        // 4: segmentation.UpdateSegmentRequest
	(*GetUserSegmentsRequest)(nil),      // 5: segmentation.GetUserSegmentsRequest
	(*GetUserSegmentsResponse)(nil),     // 6: segmentation.GetUserSegmentsResponse
	(*AssignRandomSegmentsRequest)(nil), // 7: segmentation.AssignRandomSegmentsRequest
	(*ListSegmentsRequest)(nil),         // 8: segmentation.ListSegmentsRequest
	(*ListSegmentsResponse)(nil),        // 9: segmentation.ListSegmentsResponse
	(*common.Error)(nil),                // 10: common.Error
	(*common.Response)(nil),             // 11: common.Response
}
var file_segmentation_segment_proto_depIdxs = []int32{
	0,  // 0: segmentation.GetUserSegmentsResponse.segments:type_name -> segmentation.SegmentObject
	0,  // 1: segmentation.ListSegmentsResponse.segments:type_name -> segmentation.SegmentObject
	10, // 2: segmentation.ListSegmentsResponse.error:type_name -> common.Error
	1,  // 3: segmentation.SegmentService.CreateSegment:input_type -> segmentation.CreateSegmentRequest
	3,  // 4: segmentation.SegmentService.DeletSegment:input_type -> segmentation.DeleteSegmentRequest
	4,  // 5: segmentation.SegmentService.UpdateSegment:input_type -> segmentation.UpdateSegmentRequest
	5,  // 6: segmentation.SegmentService.GetUserSegments:input_type -> segmentation.GetUserSegmentsRequest
	7,  // 7: segmentation.SegmentService.AssignRandomSegments:input_type -> segmentation.AssignRandomSegmentsRequest
	8,  // 8: segmentation.SegmentService.ListSegments:input_type -> segmentation.ListSegmentsRequest
	2,  // 9: segmentation.SegmentService.CreateSegment:output_type -> segmentation.CreateSegmentResponse
	11, // 10: segmentation.SegmentService.DeletSegment:output_type -> common.Response
	11, // 11: segmentation.SegmentService.UpdateSegment:output_type -> common.Response
	6,  // 12: segmentation.SegmentService.GetUserSegments:output_type -> segmentation.GetUserSegmentsResponse
	11, // 13: segmentation.SegmentService.AssignRandomSegments:output_type -> common.Response
	9,  // 14: segmentation.SegmentService.ListSegments:output_type -> segmentation.ListSegmentsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_segmentation_segment_proto_init() }
func file_segmentation_segment_proto_init() {
	if File_segmentation_segment_proto != nil {
		return
	}
	file_segmentation_segment_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_segmentation_segment_proto_rawDesc), len(file_segmentation_segment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_segmentation_segment_proto_goTypes,
		DependencyIndexes: file_segmentation_segment_proto_depIdxs,
		MessageInfos:      file_segmentation_segment_proto_msgTypes,
	}.Build()
	File_segmentation_segment_proto = out.File
	file_segmentation_segment_proto_goTypes = nil
	file_segmentation_segment_proto_depIdxs = nil
}
